//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desactivadas.
        /// </summary>
        internal static string ayuda1 {
            get {
                return ResourceManager.GetString("ayuda1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Embrague automático.
        /// </summary>
        internal static string ayuda2 {
            get {
                return ResourceManager.GetString("ayuda2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activadas.
        /// </summary>
        internal static string ayuda3 {
            get {
                return ResourceManager.GetString("ayuda3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayudas.
        /// </summary>
        internal static string ayudas {
            get {
                return ResourceManager.GetString("ayudas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a carreras.
        /// </summary>
        internal static string carreras {
            get {
                return ResourceManager.GetString("carreras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manuales.
        /// </summary>
        internal static string cautions1 {
            get {
                return ResourceManager.GetString("cautions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automáticos.
        /// </summary>
        internal static string cautions2 {
            get {
                return ResourceManager.GetString("cautions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clima dinámico.
        /// </summary>
        internal static string clima1 {
            get {
                return ResourceManager.GetString("clima1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lluvia.
        /// </summary>
        internal static string clima2 {
            get {
                return ResourceManager.GetString("clima2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a con lluvia.
        /// </summary>
        internal static string clima3 {
            get {
                return ResourceManager.GetString("clima3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clima.
        /// </summary>
        internal static string clima4 {
            get {
                return ResourceManager.GetString("clima4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gracias, te responderemos lo antes posible.
        /// </summary>
        internal static string contacto {
            get {
                return ResourceManager.GetString("contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta eliminada correctamente.
        /// </summary>
        internal static string cuentaeliminada {
            get {
                return ResourceManager.GetString("cuentaeliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organiza tu campeonato fácilmente.
        /// </summary>
        internal static string default1 {
            get {
                return ResourceManager.GetString("default1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Más info aquí.
        /// </summary>
        internal static string default2 {
            get {
                return ResourceManager.GetString("default2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comienza el.
        /// </summary>
        internal static string default3 {
            get {
                return ResourceManager.GetString("default3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscríbete.
        /// </summary>
        internal static string default4 {
            get {
                return ResourceManager.GetString("default4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descarga Mod.
        /// </summary>
        internal static string descarga1 {
            get {
                return ResourceManager.GetString("descarga1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar aquí.
        /// </summary>
        internal static string descarga2 {
            get {
                return ResourceManager.GetString("descarga2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dia.
        /// </summary>
        internal static string dia {
            get {
                return ResourceManager.GetString("dia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dia/Hora.
        /// </summary>
        internal static string diahora {
            get {
                return ResourceManager.GetString("diahora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dia de la semana.
        /// </summary>
        internal static string diasemana {
            get {
                return ResourceManager.GetString("diasemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentos.
        /// </summary>
        internal static string docs1 {
            get {
                return ResourceManager.GetString("docs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domingo.
        /// </summary>
        internal static string domingo {
            get {
                return ResourceManager.GetString("domingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a minutos.
        /// </summary>
        internal static string duracion1 {
            get {
                return ResourceManager.GetString("duracion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a vueltas.
        /// </summary>
        internal static string duracion2 {
            get {
                return ResourceManager.GetString("duracion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes seleccionar al menos un coche.
        /// </summary>
        internal static string errorcoche {
            get {
                return ResourceManager.GetString("errorcoche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de la carrera está dentro del plazo de inscripción.
        /// </summary>
        internal static string errorfecha {
            get {
                return ResourceManager.GetString("errorfecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado pista.
        /// </summary>
        internal static string estadopista {
            get {
                return ResourceManager.GetString("estadopista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ninguno.
        /// </summary>
        internal static string fastrepairs {
            get {
                return ResourceManager.GetString("fastrepairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora carreras.
        /// </summary>
        internal static string horacarreras {
            get {
                return ResourceManager.GetString("horacarreras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incidentes.
        /// </summary>
        internal static string incidentes {
            get {
                return ResourceManager.GetString("incidentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ven y disfruta del campeonato.
        /// </summary>
        internal static string info1 {
            get {
                return ResourceManager.GetString("info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a formado por.
        /// </summary>
        internal static string info2 {
            get {
                return ResourceManager.GetString("info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a y que transcurrirá desde el.
        /// </summary>
        internal static string info3 {
            get {
                return ResourceManager.GetString("info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a al.
        /// </summary>
        internal static string info4 {
            get {
                return ResourceManager.GetString("info4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al inscribir al piloto.
        /// </summary>
        internal static string inscr_error {
            get {
                return ResourceManager.GetString("inscr_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El piloto indicado no existe.
        /// </summary>
        internal static string inscr_noexiste {
            get {
                return ResourceManager.GetString("inscr_noexiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El piloto ya está inscrito en este evento.
        /// </summary>
        internal static string inscr_ya {
            get {
                return ResourceManager.GetString("inscr_ya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coches asignados correctamente.
        /// </summary>
        internal static string insc_coches {
            get {
                return ResourceManager.GetString("insc_coches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piloto inscrito correctamente.
        /// </summary>
        internal static string insc_inscribe {
            get {
                return ResourceManager.GetString("insc_inscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jueves.
        /// </summary>
        internal static string jueves {
            get {
                return ResourceManager.GetString("jueves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de acceso incorrectos.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lunes.
        /// </summary>
        internal static string lunes {
            get {
                return ResourceManager.GetString("lunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Martes.
        /// </summary>
        internal static string martes {
            get {
                return ResourceManager.GetString("martes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción realizada.
        /// </summary>
        internal static string mensaje1 {
            get {
                return ResourceManager.GetString("mensaje1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya estás inscrito.
        /// </summary>
        internal static string mensaje2 {
            get {
                return ResourceManager.GetString("mensaje2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce tus datos de acceso primero.
        /// </summary>
        internal static string mensaje3 {
            get {
                return ResourceManager.GetString("mensaje3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario indicado no está registrado o los datos son incorrectos.
        /// </summary>
        internal static string mensaje4 {
            get {
                return ResourceManager.GetString("mensaje4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mes.
        /// </summary>
        internal static string mes {
            get {
                return ResourceManager.GetString("mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miercoles.
        /// </summary>
        internal static string miercoles {
            get {
                return ResourceManager.GetString("miercoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se han publicado resultados del campeonato.
        /// </summary>
        internal static string noresultados {
            get {
                return ResourceManager.GetString("noresultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin límite de inscripciones.
        /// </summary>
        internal static string nummax1 {
            get {
                return ResourceManager.GetString("nummax1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limitado a.
        /// </summary>
        internal static string nummax2 {
            get {
                return ResourceManager.GetString("nummax2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a inscritos.
        /// </summary>
        internal static string nummax3 {
            get {
                return ResourceManager.GetString("nummax3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ORGANIZADOR.
        /// </summary>
        internal static string organizador {
            get {
                return ResourceManager.GetString("organizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paradas.
        /// </summary>
        internal static string paradas {
            get {
                return ResourceManager.GetString("paradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pdte. Publicar.
        /// </summary>
        internal static string pdtepublicar {
            get {
                return ResourceManager.GetString("pdtepublicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pdte. Validar.
        /// </summary>
        internal static string pdtevalidar {
            get {
                return ResourceManager.GetString("pdtevalidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Morning.
        /// </summary>
        internal static string periodo1 {
            get {
                return ResourceManager.GetString("periodo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Afternoon.
        /// </summary>
        internal static string periodo2 {
            get {
                return ResourceManager.GetString("periodo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Late afternoon/Night.
        /// </summary>
        internal static string periodo3 {
            get {
                return ResourceManager.GetString("periodo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piloto.
        /// </summary>
        internal static string piloto {
            get {
                return ResourceManager.GetString("piloto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publicado.
        /// </summary>
        internal static string publicado {
            get {
                return ResourceManager.GetString("publicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario registrado con éxito.
        /// </summary>
        internal static string registro_e0 {
            get {
                return ResourceManager.GetString("registro_e0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario indicado ya existe.
        /// </summary>
        internal static string registro_e1 {
            get {
                return ResourceManager.GetString("registro_e1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario registrado con éxito.
        /// </summary>
        internal static string registro_e2 {
            get {
                return ResourceManager.GetString("registro_e2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Faltan datos.
        /// </summary>
        internal static string registro_e3 {
            get {
                return ResourceManager.GetString("registro_e3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sabado.
        /// </summary>
        internal static string sabado {
            get {
                return ResourceManager.GetString("sabado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida: En parado.
        /// </summary>
        internal static string salida1 {
            get {
                return ResourceManager.GetString("salida1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida: Lanzada.
        /// </summary>
        internal static string salida2 {
            get {
                return ResourceManager.GetString("salida2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a segundos.
        /// </summary>
        internal static string segundos {
            get {
                return ResourceManager.GetString("segundos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        internal static string si {
            get {
                return ResourceManager.GetString("si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver aquí.
        /// </summary>
        internal static string stream {
            get {
                return ResourceManager.GetString("stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las carreras se corren los.
        /// </summary>
        internal static string textolocal1 {
            get {
                return ResourceManager.GetString("textolocal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a las.
        /// </summary>
        internal static string textolocal2 {
            get {
                return ResourceManager.GetString("textolocal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver clasificación completa.
        /// </summary>
        internal static string vercompleta {
            get {
                return ResourceManager.GetString("vercompleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viernes.
        /// </summary>
        internal static string viernes {
            get {
                return ResourceManager.GetString("viernes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No especificadas.
        /// </summary>
        internal static string vueltas {
            get {
                return ResourceManager.GetString("vueltas", resourceCulture);
            }
        }
    }
}
